
stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/data_ingestion_pipeline.py
    deps: 
      - src/cnnClassifier/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - Artifacts/data_ingestion/animals

  prepare_basemodel:
    cmd: python src/cnnClassifier/pipeline/prepair_basemodel_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/prepair_basemodel_pipeline.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - Artifacts/prepare_base_model

  model_training:
    cmd: python src/cnnClassifier/pipeline/model_training_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/model_training_pipeline.py
      - config/config.yaml
      - Artifacts/data_ingestion/animals
      - Artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - Artifacts/training/model.h5

  model_evaluation:
    cmd: python src/cnnClassifier/pipeline/evolute_model_pipeline_mlflow.py
    deps:
      - src/cnnClassifier/pipeline/evolute_model_pipeline_mlflow.py
      - Artifacts/training/model.h5
      - Artifacts/data_ingestion/animals
      - config/config.yaml
    outs:
      - scores.json:
          cache: false
